<?php
return [
    'cashbank' => [
        'DROPING_UJO' => 'DRO',
        'RECEIVE_UJO' => 'RDO',
        'UJO' => 'UJO',
        'CASH_OUT' => 'KOU',
        'CASH_IN' => 'KIN',
        'BANK_OUT' => 'BOU',
        'BANK_IN' => 'BIN',
        'BOOK_TRANSFER' => 'PBK',
        'CLOSING_UJO' => 'CJO',
        'AR_PAYMENT' => 'AR',
        'AP_PAYMENT' => 'AP',
        'ARP_PAYMENT' => 'ARP',
        'ARP_CLEARANCE' => 'ARC',
        'DOCUMENT' => 'DOC',
        'DOCUMENT_CLOSED' => 'DCL'   
    ],
    'trx'=>[
        'PRX_PURCHASE_REQUEST' => 'PRO',
        'PRX_PURCHASE_ORDER' => 'PO',
        'PRX_INVOICE' => 'IV',
        'PRX_JOB_EXPENSE' => 'JEX',
        'PRX_INVENTORYOUT' => 'PBG',
        'PRX_TRANSFEROUT' => 'ITO',
        'PRX_TRANSFERIN' => 'ITI',
        'FLEET_AUTHORIZE' => 'IO',
        'PURCHASE_REQUEST_GENERAL' => 'PEG',
        'PURCHASE_ORDER_GENERAL' => 'POG',
        'INVOICE_RECEIVE_GENERAL' => 'LPB',
        'INVOICE_OTHER_GENERAL' => 'IBG',
        'INVOICE_RETUR_GENERAL' => 'IRG',
        'INVENTORY_TRANSFER_OUT' => 'ITO',
        'INVENTORY_TRANSFER_IN' => 'ITI',
        'INVENTORY_ISSUE_GENERAL' => 'PBG',
        'INVENTORY_RISSUE_GENERAL' => 'RBG',
        'INVENTORY_STOCK_REQUEST' => 'ISR',
        'INVENTORY_PRODUCTION_MATERIAL' => 'IPM',
        'INVENTORY_PRODUCTION_RESULT' => 'IPR',
        'INVENTORY_STOCK_OPNAME' => 'ISO',
        'APINVOICE' => 'AP',
        'BANK_REQUEST' => 'CBR',
        'WORKSERVICE' => 'WOS',
    ],
    'jurnal_type'=>[
        'em_JurnalEntry'  => 0,
        'em_JurnalUJO'  => 1,
        'em_JurnalDropingUJO'  => 2,
        'em_JurnalSPJ'  => 3,
        'em_JurnalInvoice'  => 4,
        'em_JurnalCashBank'  => 5,
        'em_JurnalAPPayment'  => 6,
        'em_JurnalARPayment'  => 7,
        'em_JurnalOpname'  => 8,
        'em_JurnalOtherpayment'  => 10,
        'em_JurnalKasbon'  => 11,
        'em_JurnalPOReceive'  => 12,
        'em_JurnalAPInvoice'  => 13,
        'em_JurnalInventoryOut'  => 14,
        'em_JurnalRealisasiKasbon'  => 15,
        'em_JurnalTutupKasbon'  => 16,
        'em_JurnalPindahBuku'  => 17,
        'em_JurnalARDriver'  => 18,
        'em_JurnalARDriverPayment'  => 19,
        'em_JurnalBeginingBalance'  => 99
    ]
];